### ISSUE TITLE
Helper defines clutters scope

### ISSUE THREAD

**Issue by johandc** [dagostinelli/hypatia#16]
https://github.com/dagostinelli/hypatia/blob/06d19c1b0c21d4a9a03608232a21316c85fa670d/hypatia.h#L2066

Remember to #undef these after use, so they do not clutter or collide with outside scope.

**Comment by dagostinelli** [comment]
Doable. I'll get them cleaned up.

**Comment by dagostinelli** [comment]
This is now solved in master branch.  It will be in next release as well.
